name: Build Docker image

on:
  push:
    branches: main

env:
  PLATFORMS: |
    [
      "linux/386",
      "linux/amd64",
      "linux/arm/v6",
      "linux/arm/v7",
      "linux/arm64",
      "linux/ppc64le",
      "linux/s390x"
    ]
  CACHE_REPO: "alnmawi/build-cache"
  DOCKERHUB_REPO: "${{ github.repository }}"

jobs:
  get-platforms:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.generate-platforms.outputs.platforms }}
    steps:
      -
        name: Generate platforms
        id: generate-platforms
        run: |
          echo "::set-output name=platforms::${PLATFORMS//$'\n'/'%0A'}"

  build:
    needs: get-platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.get-platforms.outputs.platforms) }}
    steps:
      -
        name: Generate cache
        id: cache
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          echo "::set-output name=cache::${CACHE_REPO}:${DOCKERHUB_REPO////-}-${PLATFORM////-}"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=${{ steps.cache.outputs.cache }}
          cache-to: type=registry,ref=${{ steps.cache.outputs.cache }},mode=max

  publish:
    needs: [get-platforms, build]
    runs-on: ubuntu-latest
    steps:
      -
        name: Generate caches
        id: caches
        run: |
          for platform in ${{ join(fromJSON(needs.get-platforms.outputs.platforms), ' ') }}; do
            cache="type=registry,ref=${CACHE_REPO}:${DOCKERHUB_REPO////-}-${platform////-}"
            if [ -z "${caches}" ]; then
              caches="${cache}"
            else
              caches="${caches}"$'\n'"${cache}"
            fi
          done
          echo "::set-output name=caches::${caches//$'\n'/'%0A'}"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ join(fromJSON(needs.get-platforms.outputs.platforms), ',') }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Publish images
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ join(fromJSON(needs.get-platforms.outputs.platforms), ',') }}
          cache-from: ${{ steps.caches.outputs.caches }}
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest
