name: Build Docker image

on:
  push:
    branches: main

env:
  PLATFORMS: |
    [
      "linux/386",
      "linux/amd64",
      "linux/arm/v6",
      "linux/arm/v7",
      "linux/arm64",
      "linux/ppc64le",
      "linux/s390x"
    ]

jobs:
  get-platforms:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.generate-platforms.outputs.platforms }}
    steps:
      -
        name: Generate platforms
        id: generate-platforms
        run: |
          echo "::set-output name=platforms::${PLATFORMS//$'\n'/'%0A'}"

  build:
    needs: get-platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.get-platforms.outputs.platforms) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }},mode=max

  publish:
    needs: [get-platforms, build]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ join(fromJSON(needs.get-platforms.outputs.platforms), ',') }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Publish images
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ join(fromJSON(needs.get-platforms.outputs.platforms), ',') }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }},mode=max
          push: true
          tags: alnmawi/github-actions-test:latest
