name: Build Docker image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          outputs: type=docker,dest=image.tar
      -
        name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: image-${{ matrix.platform }}
          path: image.tar
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
